### PR TITLE
♻️ Simplify PRNG import by defining struct externally

### PR DESCRIPTION
**Pull request by Philogy**
## Description

I moved the `PRNG` and `LazyShuffler` structs outside of `library LibPRNG` so that they could be individually imported and you didn't always have to type `LibPRNG.PRNG`.

**Note:** This is a breaking change.

## Checklist

Ensure you completed **all of the steps** below before submitting your pull request:

- [x] Ran `forge fmt`?
- [x] Ran `forge snapshot`?
- [x] Ran `forge test`?

### CODE REVIEW

**Comment by Vectorized** [comment]
😱 I’m allergic to the inconsistency. 😱

**Comment by Philogy** [comment]
> 😱 I’m allergic to the inconsistency. 😱

What inconsistency? Is this not done for the other libs, I can open larger PR to move it all. Although CI is failing me because it's not compiling for older versions, I thought top-level `using` statements were introduced in `0.8.4`

**Comment by Vectorized** [comment]
I prefer the types to be in the library itself.  
The verbose ritual of typing `LibPRNG.PRNG` reminds me that this struct belongs to the `LibPRNG` namespace.  
It gives me dopamine.

**Comment by Vectorized** [comment]
Also, this has been on the wish list on sometime. 
Not sure the team deprioritised this small syntax sugar QoL thingy over generics.

https://github.com/ethereum/solidity/issues/1100

**Pull request closed without merging**
