### PR TITLE
⚡ Optimize cdFallback()

### PR DESCRIPTION
**Pull request by z0r0z**
## Description

`let i := o`

## Checklist

Ensure you completed **all of the steps** below before submitting your pull request:

- [x] Ran `forge fmt`?
- [x] Ran `forge snapshot`?
- [x] Ran `forge test`?

_Pull requests with an incomplete checklist will be thrown out._

### CODE REVIEW

**Comment by atarapra** [comment]
@z0r0z I didn't see any optimization on here also didn't see any change `.gas-snapshot` of this.

**Comment by z0r0z** [comment]
> @z0r0z I didn't see any optimization on here also didn't see any change `.gas-snapshot` of this.

hm, does this indicate for you? https://github.com/Vectorized/solady/commit/64ee35da1255e993776f7ccf86c93c80897bfed4#r133224719

not totally sure about last commit (getting merge conflict to stop barking), but I saw a drop after making this nit initially.

**Comment by Vectorized** [comment]
Wait, lemme check on my end.

**Comment by Vectorized** [comment]
Ok, looks like no codesize nor gas diff (for non-fuzz tests).

Before:
```
[PASS] testCdCompress() (gas: 156007)
[PASS] testCdCompressDecompress(bytes) (runs: 256, μ: 792398, ~: 646866)
[PASS] testCdCompressDecompress(uint256) (runs: 256, μ: 792578, ~: 692744)
[PASS] testCdDecompressOnInvalidInput() (gas: 26080)
[PASS] testCdFallback() (gas: 5674556)
[PASS] testCdFallback(bytes,uint256) (runs: 256, μ: 1161681, ~: 1039532)
[PASS] testCdFallbackDecompressor(bytes) (runs: 256, μ: 120082, ~: 116565)
[PASS] testCdFallbackDecompressor(uint256) (runs: 256, μ: 167824, ~: 156432)
[PASS] testCdFallbackMaskTrick(uint256,uint256) (runs: 256, μ: 689, ~: 663)
[PASS] testDecompressWontRevert(bytes) (runs: 256, μ: 724743, ~: 626333)
[PASS] testFlzCompressDecompress() (gas: 1920321)
[PASS] testFlzCompressDecompress(bytes) (runs: 256, μ: 819998, ~: 675114)
[PASS] testFlzCompressDecompress2() (gas: 942068)
[PASS] test__codesize() (gas: 21712)
```

After:
```
[PASS] testCdCompress() (gas: 156007)
[PASS] testCdCompressDecompress(bytes) (runs: 256, μ: 783800, ~: 647995)
[PASS] testCdCompressDecompress(uint256) (runs: 256, μ: 817402, ~: 692744)
[PASS] testCdDecompressOnInvalidInput() (gas: 26080)
[PASS] testCdFallback() (gas: 5674556)
[PASS] testCdFallback(bytes,uint256) (runs: 256, μ: 1185201, ~: 1039827)
[PASS] testCdFallbackDecompressor(bytes) (runs: 256, μ: 120693, ~: 117627)
[PASS] testCdFallbackDecompressor(uint256) (runs: 256, μ: 166792, ~: 156605)
[PASS] testCdFallbackMaskTrick(uint256,uint256) (runs: 256, μ: 691, ~: 663)
[PASS] testDecompressWontRevert(bytes) (runs: 256, μ: 785588, ~: 624608)
[PASS] testFlzCompressDecompress() (gas: 1920321)
[PASS] testFlzCompressDecompress(bytes) (runs: 256, μ: 832846, ~: 673048)
[PASS] testFlzCompressDecompress2() (gas: 942068)
[PASS] test__codesize() (gas: 21712)
```

**Comment by z0r0z** [comment]
reeeeeee but good to confirm!

**Pull request closed without merging**
