### PR TITLE
:sparkles: Added RLE encode lib

### PR DESCRIPTION
**Pull request by Atarpara**
## Description

#396 Close.

@Vectorized Need help for testing for code comment.

## Checklist

Ensure you completed **all of the steps** below before submitting your pull request:

- [x] Ran `forge fmt`?
- [x] Ran `forge snapshot`?
- [x] Ran `forge test`?

_Pull requests with an incomplete checklist will be thrown out._

### CODE REVIEW

**Comment by Vectorized** [comment]
I'll clean up and optimize when i have better internet.

**Comment by Atarpara** [comment]
I tried various trick for optimize but unfortunately it will increase gas cost. Glad to see your trick.

**Comment by 0xClandestine** [comment]
Just noticed your PR @Atarpara went ahead and pushed some cleanup here: https://github.com/Atarpara/solady/pull/1

**Comment by Atarpara** [comment]
@Vectorized Don't merge this PR. I am thinking to add huffman encoding decoding stuff. Let me know your thought on this.

**Comment by Vectorized** [comment]
@Atarpara I think go with whatever that is:

- robust across various data inputs
- compiles to not too much bytecode
- reasonable runtime gas

Ideally, we want a LibZip.

**Comment by Atarpara** [comment]
@Vectorized  I saw some various lossless compression like huffman coding, entory encoding, deflate I don't  think any of them better than run-length compression in solidity. 
Let me know if  you have any other compression technique in mind and can be better gas perform than RLE.

**Comment by Vectorized** [comment]
I think we should try to implement [this c library](https://github.com/andyherbert/lz1/blob/master/lz.c), and rename this library to LibZip.

- The most common use case for compressing data is to store on-chain NFT pictures. This means compression ratio is more important than runtime gas, cuz the pictures will be uncompressed in a view function.

- Include a `lz77Compress` and `lz77Decompress` which takes in bytes and returns bytes.

- We may include `rleCompress` `rleDecompress` for cases where the data is perfect for RLE compression.

**Comment by malik672** [comment]
how about facebook Zstandard it provides high compression ratio and it's probably faster than lz77

**Pull request merged**
