### PR TITLE
⚡Optimize LibZip more

### PR DESCRIPTION
**Pull request by Atarpara**
## Description
Optimized version of `flzDecompress` 

## Checklist

Ensure you completed **all of the steps** below before submitting your pull request:

- [x] Ran `forge fmt`?
- [x] Ran `forge snapshot`?
- [x] Ran `forge test`?

_Pull requests with an incomplete checklist will be thrown out._

### CODE REVIEW

**Comment by Atarpara** [comment]
@clabby try this lib for your project. It is much better than run length encoding.

**Comment by Vectorized** [comment]
@Atarpara `codecopy` should be the cheapest way to zeroize any region of memory safely.

**Comment by Atarpara** [comment]
`codecopy` = 3*size + memory expansion `mload` = memory expansion

For example:- 
codecopy(mload(0x40), codesize(), 0x8000)

pop(mload(add(mload(0x40),0x7FE0)))

**Comment by Vectorized** [comment]
@Atarpara It's 3*(size/32) + memory expansion costs.

**Pull request merged**
