### PR TITLE
Fix typo in comment

### PR DESCRIPTION
**Pull request by JorgeAtPaladin**
Am auditing this for a client, mind your spelling optimizooor.

Cheers and very clean library!

\- Marco

### CODE REVIEW

**Comment by JorgeAtPaladin** [comment]
Also- Does the yul optimizooor optimize this?

```
mstore(0x40, and(add(add(arg, 0x3f), length), not(0x1f)))
```

**Comment by Vectorized** [comment]
Big thanks for finding this!

**Comment by Vectorized** [comment]
Do let your client know that Tenderly still doesn't support z0age clones. 

Only the Etherscans.

@BencicAndrej Help add support please.

**Comment by Vectorized** [comment]
Interesting. I wonder what's the use case of CWIA. :)

**Pull request merged**
