### PR TITLE
✨ add scan forward and batch set/unset to bitmap

### PR DESCRIPTION
**Pull request by estarriolvetch**
## Description

First of all, thank you for building this beautiful library! I may have some of the libraries I wrote based on solady in the future once I test it more :)

This PR ports the scan forward and batch set/unset methods to the bitmap.

Since I haven't learned foundry, I only implement the test it with javascript.

https://github.com/estarriolvetch/solidity-bits/blob/solady/test/bitmap2.js

I will port the tests once I figure out how to do it. It will be welcome if anyone wants to help me on porting the tests!

## Checklist

Ensure you completed **all of the steps** below before submitting your pull request:

- [ ] Ran `forge snapshot`?
- [v] Ran `npm run lint`?
- [ ] Ran `forge test`?

_Pull requests with an incomplete checklist will be thrown out._

### CODE REVIEW

**Comment by Vectorized** [comment]
Help me see if scanForward can use findFirstSet.

**Comment by estarriolvetch** [comment]
@Vectorized  It's using `fls` rather than `clz` now. It should reduce some operations.

To use `ffs` rather than `fls`, it will require changing the indexing within a bucket of the bitmap.

This will make scan forward more efficient, but contracts uses the old bitmap cannot upgrade to the new version because of the change in the storage layout.

Do you want to make this change?

**Comment by Vectorized** [comment]
I'd like to have the change for consistency, using the lower bits to store the lower-indexed bits.

**Comment by Vectorized** [comment]
@estarriolvetch Ok, i think i know what is `scanForward` doing. 

It is actually scanning the buckets from largest index to smallest index.

In this case, we don't need to use `ffs`.

Imo, it should be renamed to `findGreatestSet` or `findLastSet` for clarity.

**Comment by Vectorized** [comment]
I'll port the tests and merge it in probably a few days.

Thanks!

**Pull request merged**
