### PR TITLE
✨ FixedPointMathLib

### PR DESCRIPTION
**Pull request by Vectorized**
## Description

Yes, the FPM.

## Checklist

Ensure you completed **all of the steps** below before submitting your pull request:

- [x] Ran `forge snapshot`?
- [x] Ran `npm run lint`?
- [x] Ran `forge test`?

_Pull requests with an incomplete checklist will be thrown out._

### CODE REVIEW

**Comment by Atarpara** [comment]
I think average function missing in this lib. 

```
function avg(uint256 x, uint256 y) internal pure returns (uint256 z) {
        assembly {
            z := add(and(x,y), shr(1,xor(x,y)))
        }
    }
```

**Comment by Vectorized** [comment]
@Atarpara LMAO, thanks! This is the non-overflowing version right?

**Comment by Atarpara** [comment]
@Vectorized yup.

**Comment by Atarpara** [comment]
One More Function can be add in lib.
```
function abs(int256 x) internal pure returns (uint256 z) {
        assembly {
            let mask := mul(shr(255,x),not(0))
            z := xor(mask,add(mask,x))
        }
    }
```
maybe this can optimize more. @Vectorized can you look this?

**Pull request merged**
