### PR TITLE
✨ New LibString functions

### PR DESCRIPTION
**Pull request by Vectorized**
## Description

See #97 

This PR serves as a gatherer for all the new LibString functions.

## Checklist

Ensure you completed **all of the steps** below before submitting your pull request:

- [x] Ran `forge snapshot`?
- [x] Ran `npm run lint`?
- [x] Ran `forge test`?

_Pull requests with an incomplete checklist will be thrown out._

### CODE REVIEW

**Comment by Vectorized** [comment]
@Atarpara Help me check if there are any bugs or things that can improved. Thanks!

**Comment by Atarpara** [comment]
@Vectorized As per our discussion on Twitter. Solidity create deep copy of string so we don't need to create extra copy for the slicing. Create Deep Copy Only for Library function not for internal contract function.

```
pragma solidity ^0.8.17;

library st{
    function sli(string memory x) pure external returns(string memory result){
    assembly {  
      let ptr := x
      mstore(ptr, 0x04)
      mstore(add(ptr,0x20), 0x6161626100000000000000000000000000000000000000000000000000000000)   
      result := ptr 
    }
}
}

contract C1{
    function sliceLibFunc(string memory s) external pure returns (string memory result, string memory c){
       result = st.sli(s);
       c = s;
    }

    function sliceContFunc(string memory s) external pure returns (string memory result, string memory c){
        result = _sliceDirect(s);
        c = s;
    }

    function _sliceDirect(string memory subject) public pure returns(string memory result){
        assembly{
            mstore(subject, sub(mload(subject), 2))
            result := subject
        }
    }
}
```
###### Output:
`sliceLibFunc("solday") -> "aaba" , "solady" `

`sliceContFunc("solday") -> "sola" , "sola" `

**Comment by Vectorized** [comment]
I don't think Solidity automatically deep copies a string passed into a function. 

```solidity

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "forge-std/Test.sol";

contract SliceDirectTest is Test {
    function testSliceDirect() public {
        string memory subject = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
        string memory slice = _sliceDirect(subject);
        console.log(subject); // This is "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".
        console.log(slice);   // This is "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" too!
    }

    function _sliceDirect(string memory subject) internal view returns (string memory result) {
        assembly {
            mstore(subject, sub(mload(subject), 10))
            result := subject
        }
    }
}
```

**Comment by Vectorized** [comment]
@Atarpara That function is external. 

Using that function will create a call and copy the entire string, which costs way more gas.

**Comment by Atarpara** [comment]
@Vectorized It Pretty Good. No need any changes.

**Pull request merged**
